# Generated by Django 4.1.5 on 2023-02-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата релиза'),
        ),
    ]
