# Generated by Django 4.1.5 on 2023-02-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Продолжительность'),
        ),
    ]
